version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: glownow-postgres
    restart: always
    environment:
      POSTGRES_USER: glownow
      POSTGRES_PASSWORD: glownow
      POSTGRES_DB: glownow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: glownow-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:

